# This is a basic workflow to help you get started with Actions

name: Netlify Development Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Development 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: "Checkout Source Code"
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    # Runs a set of commands using the runners shell
    - name: Building your Gatsby Site
      env:
          PRISMIC_REPO_NAME: ${{ secrets.PRISMIC_REPO_NAME }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_REPO_NAME }}
      run: |
        yarn install
        yarn build
      
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2.3
      with:
          publish-dir: './public'
          production-branch: main
          deploy-message: '${{ github.event.head_commit.message }}'
      env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEV_AUTH_TOKEN }}
